language: ruby
rvm:
 - 2.4
cache: bundler
gemfile: Gemfile

branches:
  only:
    - master
    
install:
  - bundle install
    
script:
  - bundle exec jekyll build
  #- bundle exec htmlproofer ./_site
